### PR TITLE
esqueleto: fix dependencies

### PR DESCRIPTION
**Pull request by mdorman**

### CODE REVIEW

**Comment by mdorman** [comment]
@peti I first tried to achieve this using:

```
  esqueleto = super.esqueleto.override {
    persistent-template = super.persistent-template_2_1_8_1;
    persistent-sqlite = super.persistent-sqlite_2_2_1;
    persistent = super.persistent_2_2_4_1;
  };
```

But I kept getting `persistent-2.5`; I tried overrideScope via monkey-see-monkey-do and that worked.  Is it possible for you to describe the difference concisely?

**Comment by peti** [comment]
A normal `override` replaces a build input in the package you're compiling but not in the other dependencies that package may have. For example, suppose you override `transformers` to version 5 in package `foo`, but `foo` also depends on `mtl` which is build with `transformers` version 4. Then Cabal will choose version for the build of `foo`, too, because otherwise the binary would be broken.

`overrideScope`, on the other hand, replaces the overriden package everywhere, i.e. also in other build inputs. So that error does not happen.

**Comment by peti** [comment]
BTW, can you please re-base this PR relative to the current `haskell-updates` branch?

**Comment by mdorman** [comment]
Should be good to go

**Pull request merged**
