### PR TITLE
elm-export: jailbreak, update my packages

### PR DESCRIPTION
**Pull request by jb55**

### CODE REVIEW

**Comment by domenkozar** [comment]
@peti when will this hit nixpkgs?

**Comment by peti** [comment]
Ah, crap. I didn't realize that this PR had been submitted against `master` rather than `haskell-updates` in my repo. I've merged it manually a few minutes ago.

**Comment by domenkozar** [comment]
Thanks!

**Comment by jb55** [comment]
Oops my bad, forgot to target haskell-updates

**Pull request merged**
