### PR TITLE
Fixup install invocation for new git-annex.

### PR DESCRIPTION
**Pull request by mdorman**
The CABAL variable was changed to be BUILDER, and it not being set correctly is causing build failures (I believe).

### CODE REVIEW

**Comment by mdorman** [comment]
Confirmed

**Comment by peti** [comment]
Fixed in https://github.com/NixOS/cabal2nix/commit/eddefc235e5b4ac6a3a89508940553fa8801496b.

**Comment by mdorman** [comment]
Oh, duh, I was so focused on testing it, I didn't think about the fact that I was altering a generated file.

**Comment by peti** [comment]
Still, figuring out what is broken and how it ought to be fixed is 90% of the work. Putting that fix into the right place afterwards is easy.

**Pull request closed without merging**
