### PR TITLE
Fix and maintain lambdabot

### PR DESCRIPTION
**Pull request by abbradar**
###### Motivation for this change

Fix lambdabot!
###### Things done
- [ ] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [ ] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I wasn't able to test this because I haven't figured out how to run `hackage4nix` nowadays. What is supposed to be in "hackage" repository? Let's not merge until it's properly tested.

### CODE REVIEW

**Comment by peti** [comment]
`hackage` needs to be a checked-out copy of jttps://github.com/commercialhaskell/all-cabal-hashes.

**Comment by peti** [comment]
`hackage` needs to be a checked-out copy of https://github.com/commercialhaskell/all-cabal-hashes.

**Comment by abbradar** [comment]
```
hackage2nix: hackage/preferred-versions: openFile: does not exist (No such file or directory)
```

```
> git status
On branch hackage
Your branch is up-to-date with 'origin/hackage'.
nothing to commit, working tree clean
> git remote -v
origin  https://github.com/commercialhaskell/all-cabal-hashes (fetch)
origin  https://github.com/commercialhaskell/all-cabal-hashes (push)
```

**Comment by abbradar** [comment]
Meanwhile I've managed to fix the problem with https://github.com/NixOS/nixpkgs/commit/cd7bd0b42f5b00380168a5df423f2cc5361ed709 instead, which looks better.

**Pull request closed without merging**
