### PR TITLE
lens-action has been fixed.

### PR DESCRIPTION
**Pull request by mdorman**

### CODE REVIEW

**Comment by peti** [comment]
@mdorman, when you see a block of packages where the first one is marked as broken and the following ones are marked as "dontDistribute", then this means that the latter packages don't compile because they depend on the first one. Thus, if the package has been fixed, please remove the _entire block_ from the file; not just the first line.

**Comment by mdorman** [comment]
Ah, I hadn't quite sussed that out as the meaning of 'dontDistribute'.  Silly in retrospect.

**Comment by mdorman** [comment]
Nor had I quite thought through the implications of the whitespace.

Anyway, updated.

**Comment by peti** [comment]
Thank you for the update!

**Pull request merged**
