### PR TITLE
Haskell updates

### PR DESCRIPTION
**Pull request by domenkozar**
- fixes https://github.com/NixOS/nixpkgs/issues/32631
- adds static executable for cachix

### CODE REVIEW

**Comment by domenkozar** [comment]
Might need to find another way, this warns sometimes with:

```
/nix/store/bcrwa5b8z54xrl95ipfrq6nqhb0530yi-stdenv-linux/setup: line 1296: [: too many arguments
```

**Comment by peti** [comment]
Shall I remove that commit from the branch again to avoid re-building everything?

**Comment by domenkozar** [comment]
Yes, best to do that since it will need to change anyway.

**Comment by peti** [comment]
Done.

**Pull request merged**
